user_register:
    methods: POST
    path: /user/register
    controller: App\User\UI\Controllers\RegisterUserPostController

user_find:
    methods: GET
    path: /user/find
    controller: App\User\UI\Controllers\FindUserGetController